name: Scorch
version: 0.1
main: net.warvale.scorch.Main
author: Warvale Development Team
commands:
  setobsidiandecay:
    description: Set the time in seconds it takes obsidian to decay into lava when made with water.
  gen2d:
    description: Generates a 2d array of the whole world and prints it to console. May cause lag.
    permission: scorch.gen2d
  enchantments:
    description: See a list of all custom enchantments.
    aliases: [enchants]
  giveenchant:
    description: Get any of the enchantment crystals.
    permission: scorch.give
  lootchest:
    description: Spawn a lootchest at the desired location.
  givecratekey:
    description: Give a specified player a crate key.
    permission: scorch.give
  givevotecratekey:
    description: Give a specified player a vote crate key.
    permission: scorch.give
  givereleasecratekey:
    description: Give a specified player a release crate key.
    permission: scorch.give