name: Vanquish
version: 0.1
main: net.warvale.vanquish.Main
author: Warvale Development Team
commands:
  setobsidiandecay:
    description: Set the time in seconds it takes obsidian to decay into lava when made with water.
  guild:
    description: All guild features.
    aliases: [g]
  gen2d:
    description: Generates a 2d array of the whole world and prints it to console. May cause lag.
    permission: vanquish.gen2d
