name: Vanquish
version: 0.1
main: main.java.net.warvale.vanquish.Main
author: Warvale Development Team
commands:
  setobsidiandecay:
    description: Set the time in seconds it takes obsidian to decay into lava when made with water.
  guild:
    description: All guild features.